# Generated by Django 2.2.4 on 2021-05-31 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favbookuser', models.ManyToManyField(related_name='favbook', to='favbooksapp.Users')),
                ('uploded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='favbooksapp.Users')),
            ],
        ),
    ]
