# Generated by Django 2.2.4 on 2021-05-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='favbookuser',
        ),
        migrations.RemoveField(
            model_name='books',
            name='uploded_by',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='books',
            name='favorite',
            field=models.ManyToManyField(related_name='favbook', to='favbooksapp.User'),
        ),
        migrations.AddField(
            model_name='books',
            name='uploaded_by_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='book', to='favbooksapp.User'),
            preserve_default=False,
        ),
    ]
