# Generated by Django 3.2.1 on 2021-05-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ade',
            new_name='age',
        ),
    ]
