# Generated by Django 2.2.4 on 2021-05-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registrationapp', '0002_auto_20210526_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
