# Generated by Django 2.2.4 on 2021-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdashboard', '0002_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
