# Generated by Django 2.2.4 on 2021-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdreams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavalability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
